#+title: omcwb
#+author: Davi Raubach
#+OPTIONS: num:nil toc:nil date:nil
#+PROPERTY: header-args:lilypond :noweb yes
#+EXCLUDE_TAGS: noexport
#+LATEX_HEADER: \usepackage{nopageno}
#+LaTeX_HEADER: \usepackage{pdfpages}

#+INCLUDE: abntex2.org             :only-contents t
#+INCLUDE: abntex2-meta.org        :only-contents t
#+INCLUDE: abntex2-pretextual.org  :only-contents t


* Prefácio
Nesta composição, a leitura de um texto verbal ocupa uma posição de geração de material musical e de organizador relativo da temporalidade. Em boa parte da peça, o passar do tempo é articulado pela leitura do texto.

O poema abaixo cumpre essa função na peça foi escrito para essa ocasião.

#+begin_center

Palavra atirada contra a água\\
Salta, salta, voa\\
Pousa sobre as nuvens\\
Mergulha cada vez mais fundo\\
Cada vez mais alto\\
Seduz a língua e escoa\\
Escoa, salta, voa\\
Cada vez mais sonhada
#+end_center


* Notas de Performance

*Duração* c. 4 min

** Notação rítmica
*** Tempo estrito
Notado tradicionalmente
*** Tempo de fala
Gestos instrumentais estão associados às sílabas do texto. O/A intérprete deve executar a música levando em conta sua associação com o texto. Uma leitura mental é que determina quando tocar. Pontos e vírgulas podem ser interpretados como pausas, fraseseado e dinâmicas podem derivar também do texto.

Cabeça de nota como de semínima representa a leitura de uma sílaba para cada nota (notas mais curtas). Cabeça de nota como de mínimas representam notas que se estendem por várias sílabas (notas mais longas):

#+begin_src lilypond :file exemplo_tempo_fala.pdf :results none :exports none
  \include "org_stylesheet.ily"
% #(ly:set-option 'backend 'svg)
  #(set-global-staff-size 12)
  \score {
    \include "exemplo_tempo_fala.ily"
  }

#+end_src

#+ATTR_LATEX: :width 7cm
[[file:exemplo_tempo_fala.pdf]]


  Em geral, o ritmo instrumental deve se submeter ao ritmo da leitura. Entretanto, também deve-se levar em consideração que alguns gestos precisam de tempo hábil para a exeucução e nestes casos não há problema em suspender o tempo da leitura.


#+LATEX: \includepdf[pages=-,pagecommand={}]{omcwb_score.pdf}



